### ISSUE TITLE
IMPORTANT - Constrain execution to specific CPUs or CPU throttle

### ISSUE THREAD

**Issue by omarcardona** [microsoft/Get-NetView#14]
New execution option necessary for Azure Hosts

- Identify a way for execution to be constrained to a selected set of CPUs.  This is necessary to ensure  that diagnosis does not disrupt Guest/Container workloads.  

Two options:

1. Ideally only using Host Cores for execution.
2. Identify a way to throttle the execution such that it doesn't consume 100% CPU.

**Comment by tmolenh** [comment]
The only way to effectively accomplish this is with the CpuGroups tool. Refer to [Segregating Root VPs from Guest VPs](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/manage-hyper-v-cpugroups#segregating-root-vps-from-guest-vps).

**Comment by tmolenh** [comment]
You can also **partially** constrain execution to specific CPUs with `(Get-Process -PID $PID).ProcessorAffinity = <mask>`.

**Comment by omarcardona** [comment]
The first option is not desirable since it modifies the system configuration.  

The second option is better, however since Get-NetView would need to affinitize self, the desired processor mask from [ProcessorAffinity](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.processoraffinity?view=netframework-4.8) needs to be passed in as an input.  Please see if this is feasible.

**Comment by tmolenh** [comment]
Get-NetView isn't it's own process. Above command will set affinity on current PowerShell.exe process. However, majority of processing happens in WMI, VMMS, etc. so having it as a parameter would be misleading.

**Comment by tmolenh** [comment]
Closing because this has been superseded by #29, and the `-BackgroundThreads 0` option.
