### ISSUE TITLE
Add timeout mechanism for individual commands

### ISSUE THREAD

**Issue by walter-1** [microsoft/Get-NetView#21]
To **workaround**: check REG setting first at the four script locations calling Get-NetAdapterStatistics

$AnyConnectKey = "HKLM:\SYSTEM\CurrentControlSet\Services\vpnagent"
if (-Not (Test-Path $AnyConnectKey)) 
	{ 
	if ($Global:noNetAdapters -ne $true) {
	    $file = "Get-NetAdapterStatistics.txt"
	    [String []] $cmds = "Get-NetAdapterStatistics -IncludeHidden | Sort-Object InterfaceDescription | Format-Table -Autosize  | Out-String -Width $columns",
				"Get-NetAdapterStatistics -IncludeHidden | Sort-Object InterfaceDescription | Format-Table -Property * -Autosize | Out-String -Width $columns"
	    ExecCommandsAsync -OutDir $dir -File $file -Commands $cmds
	}
}

**Comment by tmolenh** [comment]
We probably need some timeout mechanism to prevent this and similar issues.

**Comment by walter-1** [comment]
Info on root cause: the related LTE OS bug is here: 
  https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/27692990
  Get-NetAdapterStatistics cmdlet causes infinite loop in WmiPrvSE.exe if the device has LTE (Wwan) modem.

**Comment by tmolenh** [comment]
Fixed, but with a global timeout instead: https://github.com/microsoft/Get-NetView/pull/61
