### ISSUE TITLE
Fix incorrect NIC prefix

### ISSUE THREAD

**Issue by omarcardona** [microsoft/Get-NetView#28]
The pNIC.Hidden directory is incorrectly named.  It contains Software/Virtual NICs.  

Recommended changes:

1. Refactor the directory to NIC.Hidden
2. use swNIC for SW NICs
3. use pNIC if it is a Physical NIC
4. use vNIC if it's a Virtual NIC.

Avoid marking the SW NICs as vNICs.  swNIC is a better naming.  Specifically because they are not part of the Virtualization stack.  Marking them as vNICs will be confusing to non-network folks.

**Comment by tmolenh** [comment]
Identifying if something is a "vNIC" or a "swNIC" isn't really practical. We would need to maintain a list of drivers that are considered vNICs or something like that.

**Comment by omarcardona** [comment]
No necessarily.  hNIC, pNIC, and vmNIC have distinguishing values.  Just a matter of finding a similar mechanism for swNICs.  

For now you can address this by dropping the prefix for everything in the NIC.hidden directory.

**Comment by tmolenh** [comment]
Another issue is that swNIC is a non-standard term.

**Comment by omarcardona** [comment]
Neither is hNIC, vNIC or pNIC :-).
