### ISSUE TITLE
Execution time display requires column alignment

### ISSUE THREAD

**Issue by omarcardona** [microsoft/Get-NetView#35]
Execution time display requires column alignment {0,6:n0} or similar.

(35 ms) Stop-NetEventSession   NetRundown                                                                                                                                                                  (31 ms) Remove-NetEventSession NetRundown
(171 ms) netsh dump
(55 ms) netsh interface ipv4 show icmpstats
(54 ms) netsh interface ipv4 show ipstats
(59 ms) netsh interface ipv4 show tcpstats
(62 ms) netsh interface ipv4 show udpstats
(57 ms) netsh interface ipv6 show ipstats
(54 ms) netsh interface ipv6 show tcpstats
(56 ms) netsh interface ipv6 show udpstats
(63 ms) netsh -?
(70 ms) netsh trace show scenarios
(11 ms) Get-ChildItem -Path C:\DELETEME\msdbg.WORKSTATION -Exclude Get-NetView.log -File -Recurse | Get-FileHash -Algorithm SHA1 | Format-Table -AutoSize | Out-String -Width 4096
(2 ms) Get-FileHash -Path "C:\DELETEME\Get-NetView.ps1" -Algorithm SHA1 | Format-List -Property * | Out-String -Width 4096

**Comment by tmolenh** [comment]
Fixed by e627e4311deec50aad8b6a46369e9e2a7a6c7728.
