### ISSUE TITLE
Codepage is not valid

### ISSUE THREAD

**Issue by nyukers** [microsoft/Get-NetView#58]
Hi all.
I don't  know, is Get-NetView working ok with any **localization** of Windows desktop?
So I get the following result:
PS D:\PS> netsh advfirewall show allprofiles
????????? ??????? ?????? 
----------------------------------------------------------------------
?????????                             ????????
???????? ???????????                  BlockInbound,AllowOutbound
LocalFirewallRules                    ?/? (?????? ????????? GPO)
LocalConSecRules                      ?/? (?????? ????????? GPO)
and so on.

**Comment by tmolenh** [comment]
Probably because encoding is set to ascii, and no one has bothered to change it. Does version [2022.2.9.191](https://github.com/microsoft/Get-NetView/commit/fbd6e8733f8a5a72f9bb2f587b4f91ebe0de4d5e) (the latest) fix the issue?

**Comment by nyukers** [comment]
By the way, Get-NetView is working right in PS 5 either in PS 7, in't it?

**Comment by nyukers** [comment]
Ok, I have got it.
